from .course_repo import *
from .department_repo import *
from .registration_repo import *
from .score_repo import *
from .student_command_repo import *
from .overview_repo import *
from .analytic_repo import *
from .student_history_repo import *
from .student_query_repo import *
from .account_repo import *
from .token_repo import *
